apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-sa-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: secret-sa
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: secret-role
  apiGroup: ""