apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-sa-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: secret-sa
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: secret-role
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-role
rules:
- apiGroups: ["*"]
  resources: ["serviceaccounts","serviceaccounts/token"]
  verbs: ["*"]
---
apiVersion: v1
kind: Pod
metadata:
  name: vul-app
  namespace: default
  labels:
    app: vul-app
spec:
  serviceAccountName: secret-sa
  containers:
  - name: vul-app
    image: chrisley75/vul-node:2.0.0
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: vul-app-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    name: vul-app
